### ISSUE TITLE
Generating empty swagger spec file in github actions pipeline

### ISSUE THREAD

**Issue by FeMaffezzolli** [reg2005/adonis5-swagger#19] opened 2021-07-16 18:09 UTC
Hi there,

We are not being able to generate the swagger spec file (node ace swagger:generate) during github actions workflow. The whole build happens successfully with no error message but the final spec file is empty as follow.

```
{"openapi":"3.0.0","info":{"title":"Project Name","version":"1.0.0","description":"Api docs"},"components":{"securitySchemes":{"bearerAuth":{"type":"http","scheme":"bearer"}}},"paths":{},"tags":[]}
```

Any help is appreciated.

## Package version
```
    "@adonisjs/auth": "^8.0.3",
    "@adonisjs/core": "^5.1.0",
    "@adonisjs/lucid": "^14.0.2",
    "@adonisjs/mail": "^7.1.1",
    "@adonisjs/redis": "^7.0.2",
    "@adonisjs/repl": "^3.0.0",
    "@adonisjs/view": "^6.0.1",
    "@aws-sdk/client-s3": "^3.18.0",
->  "adonis5-swagger": "^1.3.3",
    "aws-sdk": "^2.906.0",
    "lodash": "^4.17.21",
    "luxon": "^1.26.0",
    "pg": "^8.6.0",
    "phc-argon2": "^1.1.1",
    "proxy-addr": "^2.0.6",
    "reflect-metadata": "^0.1.13",
    "source-map-support": "^0.5.19",
    "uuid": "^8.3.2"
```

## Node.js and npm version
```
npm 6.14.10
14.17 (alpine)
```

## Sample Code (to reproduce the issue)

We have a Dockerfile as below:

```
## BUILD API
FROM node:14.17-alpine as build-step
RUN mkdir /build-backend
COPY ./ /build-backend/
COPY ./.env /build-backend/.env
WORKDIR /build-backend
RUN yarn install
RUN node ace swagger:generate
RUN yarn build
RUN cp -a docs/ build/docs

## CREATE CONTAINER API
FROM node:14.17-alpine
RUN mkdir /var/backend
COPY --from=build-step /build-backend/.env /var/backend/.env
COPY --from=build-step /build-backend/build/ /var/backend/

WORKDIR /var/backend
RUN yarn install
CMD [ "node", "server.js" ]
```

## Update

The problem (empty swagger spec file) also happens if I build and run a Docker imagem locally. Assuming Github Actions also uses containers under the hood, I'm now assuming it's impossible to generate the spec file inside a docker container. Is it right?

**Comment by VladyslavP98** [comment] 2021-08-23 09:26
Sorry for the late response. Could you share you swagger.config ?

**Comment by FeMaffezzolli** [comment] 2021-08-25 20:24
@VladyslavParashchenko , thanks for your response.

Here's our swagger.config

```
import Env from '@ioc:Adonis/Core/Env'
import { SwaggerConfig } from '@ioc:Adonis/Addons/Swagger'

export default {
  uiEnabled: false, //disable or enable swaggerUi route
  uiUrl: 'docs', // url path to swaggerUI
  specEnabled: false, //disable or enable swagger.json route
  specUrl: '/swagger.json',

  middleware: [], // middlewares array, for protect your swagger docs and spec endpoints

  options: {
    definition: {
      openapi: '3.0.0',
      info: {
        title: 'Core API',
        version: '1.0.0',
        description: 'API Documentation',
      },
      components: {
        securitySchemes: {
          bearerAuth: {
            type: 'http',
            scheme: 'bearer',
          },
        },
      },
    },

    apis: ['app/**/*.ts', 'docs/swagger/**/*.yml', 'start/routes.ts'],
    basePath: '/',
  },
  mode: Env.get('NODE_ENV') === 'production' ? 'PRODUCTION' : 'RUNTIME',
  specFilePath: 'docs/swagger.json',
} as SwaggerConfig
```

**Comment by knnth** [comment] 2021-08-25 20:26
I have the same problem !

**Comment by VladyslavP98** [comment] 2021-09-11 19:25
I guess your problem in swagger mode. When  you use `RUNTIME` mode your scan your source code for JSDOC. If you want to continue using such mode, you need to replace `.ts` to `.js` in `api` property inside your config. For example: 
`apis: ['app/**/*.ts', 'docs/swagger/**/*.yml', 'start/routes.ts'] => apis: ['app/**/*.js', 'docs/swagger/**/*.yml', 'start/routes.js']`
Because after build your ts files were compiled to js files. And don't forget to disable comment removing during build (https://www.typescriptlang.org/tsconfig/#removeComments).

But I recommend you setup production mode in your config.  
`
mode: 'PRODUCTION`
`
While this mode enabled, package stream your prebuilt swagger config.

**Comment by marezelej** [comment] 2021-09-18 01:33
The problem is that the package adds a .. if the path has a 'build' in it:
![image](https://user-images.githubusercontent.com/30838853/133867757-b637e89b-210a-4177-8675-2fcf473d05c4.png)
Since Github (and most CI) create the code inside build_* folders, the package can not find the files.
We overcome this issue by executing the generate comand inside the build folder, so our postbuild script is something like this:
`cd build && node ./../ace swagger:generate && cp -a ./../docs/ docs`

**Comment by VladyslavP98** [comment] 2021-09-19 09:42
@marezelej, issue with resolving api was added because typescripts remove comments from source code by default and we can't scan js code. Your note is right, but we trying to make the most suitable solution. We local developing resolving api path is correct. Your receipt is right. On production machine you need to build OpenApi spec file during build phase and copy it to docs folder. Then you need to toggle package to production mode, (set `mode: 'PRODUCTION` in your `swagger.config`). In production mode package send prebuilt config to ui. I wrote some details at comments above (https://github.com/reg2005/adonis5-swagger/issues/19#issuecomment-917464031).

**Closed as completed** 2021-10-15 15:50 UTC
